// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_draft_message_and_status_to_messages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_draft_message_and_status_to_messages));
        
        string IMigrationMetadata.Id
        {
            get { return "202106041542169_mig_draft_message_and_status_to_messages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
